# Generated by Django 3.1.3 on 2020-11-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_subjectcategory_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcategory',
            name='photo',
        ),
    ]
