# Generated by Django 2.2 on 2020-11-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201123_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookimage',
            field=models.ImageField(null=True, upload_to='static/img/book', verbose_name='Картинка'),
        ),
    ]
