# Generated by Django 2.2 on 2020-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_books_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='avtorphoto',
            field=models.ImageField(null=True, upload_to='static/img/avtor', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookimage',
            field=models.ImageField(null=True, upload_to='static/img/book', verbose_name='Картинка'),
        ),
    ]
