# Generated by Django 2.2 on 2020-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201123_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/catalog', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='books',
            name='avtorphoto',
            field=models.ImageField(null=True, upload_to='static/img/avtor', verbose_name='Фото автора'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookimage',
            field=models.ImageField(null=True, upload_to='static/img/book', verbose_name='Обложка книги'),
        ),
    ]
