# Generated by Django 2.2 on 2020-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201123_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='industries',
            field=models.CharField(blank=True, choices=[('w', 'Военная история'), ('c', 'История культуры'), ('s', 'История науки'), ('r', 'История государства и права '), ('p', 'История политических и правовых учений'), ('re', 'История религии'), ('e', 'История экономики')], default='w', max_length=2),
        ),
    ]
