# Generated by Django 2.2 on 2020-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201124_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='avtordesc',
            field=models.TextField(blank=True),
        ),
    ]
