# Generated by Django 3.1.2 on 2020-12-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_personality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personality',
        ),
    ]
